### ISSUE TITLE
Error on upgrade to PHP 8

### ISSUE THREAD

**Issue by chrisdpeters** [stackpath/stackpath-wordpress#10]
Hi, when trying to upgrade to PHP 8, we get this error for some admin users. This is on literally every `/wp-admin/*` based pageview while an admin is logged in.

```
PHP Fatal error: Uncaught TypeError: array_shift(): Argument #1 ($array) must be of type array, null given in /wp-content/plugins/stackpath-wordpress/src/WordPress/Plugin.php:191
Stack trace:
#0 /wp-content/plugins/stackpath-wordpress/src/WordPress/Plugin.php(191): array_shift(NULL)
#1 /wp-includes/class-wp-hook.php(307): StackPath\\WordPress\\Plugin->StackPath\\WordPress\\{closure}('')
#2 /wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array)
#3 /wp-includes/plugin.php(474): WP_Hook->do_action(Array)
#4 /wp-admin/includes/menu.php(155): do_action('admin_menu', '')
#5 /wp-admin/menu.php(394): require_once('/nas/content/li...')
#6 /wp-admin/admin.php(158): require('/nas/content/li...')
#7 /wp-admin/index.php(10): require_once('/nas/content/li...')
#8 {main}
 thrown in wp-content/plugins/stackpath-wordpress/src/WordPress/Plugin.php on line 191, referer: https://example.com/wp-login.php?redirect_to=https%3A%2F%2Fexample.com%2Fwp-admin%2F&reauth=1
```

Unfortunately, I've had to disable the Stackpath plugin as I made some other changes that don't allow us to downgrade back to PHP 7.4 easily.

**Comment by jboonstra** [comment]
Though I believe the StackPath / WordPress plugin is currently unmaintained, my PR #13 does address this issue.
