### ISSUE TITLE
Critical errors on WordPress 6.2

### ISSUE THREAD

**Issue by jboonstra** [stackpath/stackpath-wordpress#11]
This plugin will generate a critical error in various places on WordPress 6.2 (and presumably newer) due to its reliance on/assumption that the `Requests_Response` class is being used by WordPress, when converting Responses to Stackpath's own Response class.

I'll be creating a PR shortly to address the critical errors, though there are other refactors necessary since `Requests_Response` has been deprecated for awhile now in favor of `WpOrg\Requests\Response`.

**Comment by jeffgoh** [comment]
oh perfect - thanks so much @jboonstra - this was just what I was looking for.
This was the error message _before_ applying the PR and after applying your PR it works great.
Can I check if the code is PHP8.x ready?  

```
[30-Apr-2023 10:38:38 UTC] PHP Fatal error:  Uncaught Error: Call to undefined method WpOrg\Requests\Response::decodeBody() in /web/linux/wordpress/wp-content/plugins/stackpath-wordpress/src/API/Client.php:182
Stack trace:
#0 /web/linux/wordpress/wp-content/plugins/stackpath-wordpress/src/API/Client.php(221): StackPath\API\Client->request('POST', '/identity/v1/oa...', Array)
#1 /web/linux/wordpress/wp-content/plugins/stackpath-wordpress/src/API/Client.php(111): StackPath\API\Client->post('/identity/v1/oa...', Array)
#2 /web/linux/wordpress/wp-content/plugins/stackpath-wordpress/src/WordPress/Plugin/PostActions.php(38): StackPath\API\Client->authenticate()
#3 /web/linux/wordpress/wp-includes/class-wp-hook.php(308): StackPath\WordPress\Plugin->saveApiCredentialsPostAction('')
#4 /web/linux/wordpress/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#5 /web/linux/wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#6 /web/linux/wordpress/wp-admin/admin-post.php(85): do_action('admin_post_stac...')
#7 {main}
  thrown in /web/linux/wordpress/wp-content/plugins/stackpath-wordpress/src/API/Client.php on line 182
```
